### PR TITLE
Fix (line mode): Use line mode parameter when possible

### PR DESCRIPTION
**Pull request by phgz**
In normal callback, the call to `normal_surround` would always send false for `line_mode`.

### CODE REVIEW

**Comment by kylechui** [comment]
Is there an actual bug that this is related to? The reason that this is the case (which is something that should honestly be refactored) is because the `line_mode` variable is handled on lines 256--260. Changing that variable in the callback effectively does nothing.

**Comment by phgz** [comment]
> Is there an actual bug that this is related to?

When surrounding with a keybinding using "_line", the indentation is not made. In fact, we're back to #185.

**Comment by kylechui** [comment]
Do you mind trying the alternate branch `refactor-utils` and see if that resolves the issue?

**Comment by kylechui** [comment]
Actually in either case it should be fine; I've merged this branch in for now, and the corresponding change has been made to the other branch. Thanks again for submitting this fix!

**Comment by phgz** [comment]
> Do you mind trying the alternate branch `refactor-utils` and see if that resolves the issue?

It seems to indeed solve it! Other keymaps do not seem to be disturbed as well as far as I've tested.

**Pull request merged**
