### PR TITLE
docs: Improve issue template.

### PR DESCRIPTION
**Pull request by smjonas**
I think using `yaml` instead of `markdown` is way better for user experience because it allows things like required fields, checkboxes and non-modifiable text :D I got a bit of inspiration from [Neovim's issue template](https://raw.githubusercontent.com/smjonas/neovim/master/.github/ISSUE_TEMPLATE/bug_report.yml).
I also removed the "Describe the bug" section because there was a lot of overlap with the "To reproduce" and "Additional context" fields. Also, "Actual behavior" seemed to be missing which is why I added that instead.

I created a repo for you where you can test this out: https://github.com/smjonas/test/issues/new/choose

Let me know what you think!

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Fwiw, this is much harder to use on mobile and straight up doesn't work in the GH app. (It loads the browser.)

**Comment by smjonas** [comment]
When I open the link on mobile I am simply redirected to the website (probably this is not implemented in the app yet). Filling it out there works just fine for me.

**Comment by kylechui** [comment]
Thanks for the PR! I might defer this change until it's out of beta; at the very least until I finish pushing out some other features.

**Comment by smjonas** [comment]
Btw, I don't think this feature will be out of beta anytime soon :D It's been in beta since at least July of last year. Both Vim and Neovim have since adopted it.

**Review by kylechui — APPROVED** [review]

**Pull request merged**
