### PR TITLE
ci: enable GitHub actions for stylua, luacheck and tests

### PR DESCRIPTION
**Pull request by smjonas**
You can see an example CI run here: https://github.com/smjonas/nvim-surround/pull/1

Currently the tests are failing (locally as well), but that should be fixed separately.

### CODE REVIEW

**Comment by kylechui** [comment]
Just a quick question before I merge, is `vusted` the same testing software as what `plenary` uses? Because I feel like the tests should be passing if it's just running `surround_spec.lua`.

**Comment by smjonas** [comment]
It should be as simple as `luarocks install vusted`, then `vusted tests`. I have no real preference, but someone else would have to help with setting up GitHub actions for `plenary` then. Unless I decide to watch some tutorial on plenary later :)

> Small thing to note: the neovim/lua community has really adopted plenary, so it might be worth sticking just to keep consistent with the community.

Sure, but I mean this will only be used for GitHub actions. You can still use `plenary` locally if you prefer it.

**Comment by smjonas** [comment]
I managed to get tests working with plenary :) Though the tests are still failing with the exact error as with vusted :D @kylechui

**Review by kylechui — APPROVED** [review]

**Comment by kylechui** [comment]
Thank you so much for the help!

**Pull request merged**
