### PR TITLE
feat: add linewise deletion of surrounds

### PR DESCRIPTION
**Pull request by phgz**
Skeleton implementation for #305.

Mainly missing doc and tests.

### CODE REVIEW

**Comment by kylechui** [comment]
One minor concern that I have is how `cS` will now be interpreted, i.e. does the "line" for `S` mean that the replacement will be on new lines (as is current), or that it will delete the lines the surround is on (as you propose)? I feel that this might not be the most intuitive.

**Comment by phgz** [comment]
I see. Well personally I do not directly use `dS`, but rather `dVs` (remap) as mentioned in #305. So maybe it could directly be added as such, although I'm not sure how many people are familiar with the `force-motion` feature.

**Comment by kylechui** [comment]
Hmm... I'm personally quite wary of adding new features nowadays; I would probably like to see a few more people say that they *really* want this feature before I commit to adding it in. I personally don't think most people know about `force-motion`; many don't even know about `motion` or `text-object` :wink:

**Comment by phgz** [comment]
No problem! I'll maintain my fork hehe.

**Pull request closed without merging**
